### ISSUE TITLE
Choose time zone for "local" timestamps shown in email bodies

### ISSUE THREAD

**Issue by susnick** [datalust/seq-app-htmlemail#73]
Good Morning,
The time listed on the email notifications is UTC, I tried copying the template and changing $UtcTimestamp to $LocalTimestamp. I tried using the server timestamp option on all ingestion inputs, this also did not work. I verified all machines have correct timezone and time set. How can i make this show correctly in the email notifications?

**Comment by nblumhardt** [comment]
Thanks for the note! Unfortunately this is a quirk from the very early days of this app - the `$LocalTimestamp` field uses the time zone offset information that came with the original log event timestamp (from the source application). Since most client libraries now send UTC this isn't particularly useful anymore.

We'll need to give some thought as to how best to approach this - I'll update the ticket when we have a plan.

**Comment by nblumhardt** [comment]
@stphnlwlsh I think https://github.com/datalust/seq-app-htmlemail/pull/74 is the way forward. We've just popped out on the other side of our 2021.3 release and are gathering up our next priorities, I'll add this to the list.

**Comment by stphnlwlsh** [comment]
@nblumhardt excellent. I saw the 2021.3 release announcement and it had a lot of other things I've been desiring as well. Thanks for all the hard work!
