### ISSUE TITLE
Properties not included in alert subject

### ISSUE THREAD

**Issue by desmondgc** [datalust/seq-app-htmlemail#96]
Using: HTML Email 3.1.0-dev-00179 on Seq 2022.1

I have configured an alert:

```
select count(*) as count
from stream
where @Message like 'Hello%'
group by time(1m)
having count > 0
limit 100
```

I am sending test events with the following template: `"@mt":"Hello, {User}", "User":"desmondgc"`

If I specify a subject template like "Alert for {{User}} test" for the notification, the resulting email does not include the user value. Instead, the subject becomes:

```
Alert for  test
```

If I instead use one of the built-in properties like $Id or $EventType, the template is properly filled.

Isn't it possible to use custom properties for alert notification subject?

**Comment by nblumhardt** [comment]
Hi Desmond,

Alerts are based on aggregates, so unfortunately if 10 events occur within the 1 minute window of the alert, these might all have different values for the `User` property. If events arrive with `"User":"desmondgc"` and `"User":"nblumhardt"` there's no way for Seq to pick which username appears in the subject.

The _Include contributing events_ option on the alert notification can include multiple contributing events into the email body, however. Let me know if this helps.

Best regards,
Nick

**Comment by nblumhardt** [comment]
Hi @desmondgc - the `$Id` comes from the _notification_ event, not the events that the notification is describing the occurrence of (a bit tricky to describe, so let me know if you need more detail on that).

If you're keen to have every individual event reported as a single email, creating a separate instance of the email app in _Settings > Apps_, and using _[x] Stream incoming events_ would have that effect (instead of using an alert).

Due to the design of alerts, there's no way to accurately report properties from individual contributing events in the subject, unfortunately.
